# Generated by Django 3.2.10 on 2021-12-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favouritepost',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique-like'),
        ),
    ]
