# Generated by Django 3.2.10 on 2021-12-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useractivity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
