# Generated by Django 3.2.10 on 2022-01-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useractivity_last_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='user',
            new_name='username',
        ),
    ]
